name: Meals App CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup environment variables
        run: |
          echo "NEXT_PUBLIC_FIREBASE_API_KEY=${{ secrets.NEXT_PUBLIC_FIREBASE_API_KEY }}" >> .env.local
          echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}" >> .env.local
          echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}" >> .env.local
          echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${{ secrets.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET }}" >> .env.local
          echo "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID }}" >> .env.local
          echo "NEXT_PUBLIC_FIREBASE_APP_ID=${{ secrets.NEXT_PUBLIC_FIREBASE_APP_ID }}" >> .env.local
          echo "NEXT_PRIVATE_REDIS_HOST=${{ secrets.NEXT_PRIVATE_REDIS_HOST }}" >> .env.local
          echo "NEXT_PRIVATE_REDIS_PORT=${{ secrets.NEXT_PRIVATE_REDIS_PORT }}" >> .env.local
          echo "NEXT_PRIVATE_REDIS_USERNAME=${{ secrets.NEXT_PRIVATE_REDIS_USERNAME }}" >> .env.local
          echo "NEXT_PRIVATE_REDIS_PASSWORD=${{ secrets.NEXT_PRIVATE_REDIS_PASSWORD }}" >> .env.local

      - name: Run Gulp tasks
        run: gulp

      - name: Build Next.js app
        run: npm run build

      - name: Run tests
        run: npm test

      - name: Upload production build
        uses: actions/upload-artifact@v4
        with:
          name: nextjs-build
          path: .next
